# -*- coding: utf-8 -*-
"""reshetNueronsReduda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8cPYv9XDXovmpC5r_WD-j0YodZ0QCND
"""

import pandas as pd
import numpy as np
import seaborn as sns

def sigmoid(x):
  return 1/(1+np.exp(-x))

def feed_forward(x,w1,b1,w2,b2):
  z1 = w1@x + b1
  a1 = sigmoid(z1)
  #shold switch dimensions to a1 from 1,2 to 2,1 in some way
  z2 = a1@w2 + b2
  a2 = sigmoid(z2)
  return a2

a2 = feed_forward(np.array([1,1]),np.array([2.6,1.1]),-7.8,np.array([2.8,2.4]),-17.5)
print(a2)